name: Build and Push Docker Images

#TODO - This should not push images to ECR on every branch push. Only main should be automatically pushed to ECR.
# If feature branches need to be tested in a deployed environment, a separate workflow_dispatch should be run for those.
on:
  #push:
  #  branches:
  #    - "**"
  #  tags-ignore:
  #    - "**"
  workflow_dispatch:
    inputs:
      environment:
        description: Both Github Environment and AWS Environment
        type: environment
        required: true
        default: dev
      push-image:
        description: Push Image to ECR
        type: boolean
        required: true
        default: true
#      docker-tag:
#        description: Docker Tag
#        type: string
#        required: true

env:
  AWS_DEFAULT_OUTPUT: json
  AWS_REGION: us-west-2
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}-${{ inputs.environment }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: # these permissions must be set for AWS auth to work!
  id-token: write
  contents: read

jobs:
  build-image:
    name: Build Docker Image
    uses: ./.github/workflows/reusable-build-docker-image.yml
    with:
      environment: ${{ inputs.environment }}
      push-image: ${{ inputs.push-image }}
      branch-name: ${{ github.head_ref || github.ref_name }}
      commit-sha: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

  build-docker-image-summary:
    name: Build Result
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - name: Generate Summary
        run: |
          echo "branch-image=${{ needs.build-image.outputs.branch-image }}"
          echo "sha-image=${{ needs.build-image.outputs.sha-image }}"
          echo "| Type | Image |" >> "$GITHUB_STEP_SUMMARY"
          echo "| ---- | ----- |" >> "$GITHUB_STEP_SUMMARY"
          echo "| SHA | ${{ needs.build-image.outputs.sha-image }} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Branch | ${{ needs.build-image.outputs.branch-image }} |" >> "$GITHUB_STEP_SUMMARY"
